language: android

sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    #- sys-img-armeabi-v7a-android-19

os:
  - linux

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug -xlint

